"""
Message entity — domain object for a single message in a conversation.

Pure Python dataclass. Zero external dependencies.
Contains domain behavior including LLM format conversion.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime


@dataclass
class Message:
    """
    Represents a single message in a conversation.

    Stores either a user query or an assistant response.
    Intermediate agent steps are NOT stored here — those are tracked
    in Langfuse. Only the final user question and assistant answer are persisted.

    Fields:
        message_id: Unique UUID identifier.
        conversation_id: Parent conversation UUID.
        role: Either "user" or "assistant".
        content: The text content of the message.
        system_prompt_id: Active system prompt when this message was created.
                          Only relevant for role="assistant".
        model_id: Model used to generate this message.
                  Only relevant for role="assistant".
        token_count: Estimated tokens used. None if not yet calculated.
        created_at: UTC-aware timestamp of creation.
    """

    message_id: str
    conversation_id: str
    role: str
    content: str
    system_prompt_id: str | None = None
    model_id: str | None = None
    token_count: int | None = None
    created_at: datetime = field(default_factory=datetime.utcnow)

    def is_from_user(self) -> bool:
        """
        Return True if this message was sent by the user.

        Returns:
            True when role is "user".
        """
        return self.role == "user"

    def is_from_assistant(self) -> bool:
        """
        Return True if this message was generated by the assistant.

        Returns:
            True when role is "assistant".
        """
        return self.role == "assistant"

    def to_llm_format(self) -> dict[str, str]:
        """
        Convert this message to the OpenAI-compatible message dict format.

        This is the single location where LLM message formatting occurs.
        Service layer and client layer must never implement this conversion.

        Returns:
            Dict with "role" and "content" keys, ready for LLM API call.

        Example:
            {"role": "user", "content": "What is Pasal 5?"}
        """
        return {"role": self.role, "content": self.content}
